# Generated by Django 5.0.2 on 2024-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todor',
            name='tododone',
            field=models.BooleanField(default=False),
        ),
    ]
