# Generated by Django 5.0.2 on 2024-03-01 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todor_tododone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todor',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
